import { Inter } from 'next/font/google';
import './stock.module.scss';
import Sidebar from '../../../components/sidebar/sidebar'; 

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Stock Page',
  description: 'Generated by create next app',
};

const StockLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
};

export default StockLayout;
