/* THIS IS GONNA BE THE DASHBOARD */
/* THIS IS WHERE WERE GONNA CALL LIKE <SIDEBAR/> SOMETHING LIKE THAT*/
/* STILL DEBATING BUT I THINK I WILL HAVE SCSS FOR THIS PAGE ALONE LIKE THE OTHER PAGES THIS IS NOT TAILWIND*/