import React from 'react';
import { Inter } from 'next/font/google';
import Sidebar from '../../../components/sidebar/sidebar';
import './report.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Report Page',
  description: 'Generated by create next app',
};

const ReportLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
};

export default ReportLayout;
