import { Inter } from 'next/font/google';
import './dashboard.module.scss';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });

const Sidebar = dynamic(() => import('../../../components/sidebar/sidebar'), { ssr: false });

export const metadata = {
  title: 'Dashboard Page',
  description: 'Generated by create next app',
};

const DashboardLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
};

export default DashboardLayout;
